# Path: ~/besu_privacy_sample/privateNetwork/:/app/

# data
data-path="/Users/min/Downloads/github/besu_local_test/local4nodes/node01/data"
logging="INFO"

# private_key
node-private-key-file="/Users/min/Downloads/github/besu_local_test/local4nodes/out/keys/0x3ac3bbbb1bf081e8bbb769e47598857e970653cf/key.priv"

auto-log-bloom-caching-enabled=false
genesis-file="/Users/min/Downloads/github/besu_local_test/local4nodes/genesis_IBFT2.json"

min-gas-price=0
sync-mode="FAST"
host-whitelist=["*"]

# identity
identity="node1"

#p2p-host="0.0.0.0"
p2p-port=30303

rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545

rpc-http-api=["ADMIN","NET","ETH","WEB3","IBFT","DEBUG","TRACE","TXPOOL"]
rpc-http-cors-origins=["*"]

rpc-http-authentication-enabled=false
rpc-http-authentication-jwt-public-key-file="/Users/min/Downloads/github/besu_local_test/local4nodes/publicKey.pem"

rpc-ws-enabled=true
rpc-ws-port=8546

revert-reason-enabled=true

tx-pool-max-size=100
#tx-pool-hashes-max-size=20
#tx-pool-price-bump=10
tx-pool-retention-hours=1

#tx-pool-tx-inflow-control-enabled=true
#tx-pool-enterprise-pending-tx-sorter-enabled=true
