# Path: ~/besu_privacy_sample/privateNetwork/:/app/

# data
data-path="./node02/data"
logging="INFO"

# private_key
node-private-key-file="./out/keys/0x76ec6d2cb916f25a4bb5ee9c56a134ba73ea010f/key.priv"

auto-log-bloom-caching-enabled=false
genesis-file="./genesis.json"

min-gas-price=0
sync-mode="FULL"
#data-storage-format="BONSAI"

host-allowlist=["*"]
#banned-node-ids=["0x2b6b9b1a5eaf945ef2f3a8be52f182ffce5d26986664ed72fcdeb40dbdbfb2986aadb0af46664ce04eac916452e3be85056d73e30875f0bc00bba43fb7f731ea"]

# identity
identity="node2"

#p2p-host="0.0.0.0"
p2p-port=30304

rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8555

rpc-http-api=["ADMIN","NET","ETH","WEB3","QBFT","DEBUG","TRACE","TXPOOL"]
rpc-http-cors-origins=["*"]

rpc-ws-enabled=true
rpc-ws-port=8556

#metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9555

# https://besu.hyperledger.org/public-networks/how-to/connect/manage-peers
remote-connections-limit-enabled=false
random-peer-priority-enabled=true
revert-reason-enabled=true

#bootnodes=["enode://6ccdf5893a1ed9214c92f48b8f94fc95fb0f81614262c1ef493369fb28f967d6dff3a176dd0b1f0a901451a70626755c8101bdac92a7eea558a75b78869c09ed@127.0.0.1:30303"]
