# Path: ~/besu_privacy_sample/privateNetwork/:/app/

# data
data-path="/Users/min/Downloads/github/besu_local_test/local4nodes/node02/data"
logging="INFO"

# private_key
node-private-key-file="/Users/min/Downloads/github/besu_local_test/local4nodes/out/keys/0x3c79733f8aa07f9b7e55106b22cb9097d5887d8b/key.priv"

auto-log-bloom-caching-enabled=false
genesis-file="/Users/min/Downloads/github/besu_local_test/local4nodes/genesis_IBFT2.json"

min-gas-price=0
sync-mode="FULL"
host-whitelist=["*"]

# identity
identity="node2"

#p2p-host="0.0.0.0"
p2p-port=30304

rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8555

rpc-http-api=["ADMIN","NET","ETH","WEB3","IBFT","DEBUG","TRACE","TXPOOL"]
rpc-http-cors-origins=["*"]

rpc-ws-enabled=true
rpc-ws-port=8556

revert-reason-enabled=true

tx-pool-max-size=100
#tx-pool-price-bump=10
tx-pool-retention-hours=1

bootnodes=["enode://6ccdf5893a1ed9214c92f48b8f94fc95fb0f81614262c1ef493369fb28f967d6dff3a176dd0b1f0a901451a70626755c8101bdac92a7eea558a75b78869c09ed@127.0.0.1:30303"]

#tx-pool-tx-inflow-control-enabled=true
#tx-pool-enterprise-pending-tx-sorter-enabled=true
