# Path: ~/besu_privacy_sample/privateNetwork/:/app/
# https://skchainz.atlassian.net/wiki/spaces/CHAINZ/pages/26509355/ChainZ+Mainnet+As-Is+To-Be
# https://besu.hyperledger.org/en/21.10.9/Reference/CLI/CLI-Syntax/

# data
data-path="./node01/data"
logging="INFO"

# private_key
node-private-key-file="../1node/out/keys/0xe88550bebd195433d429ec9f3e737ec2d2e02dcf/key.priv"

auto-log-bloom-caching-enabled=false
genesis-file="./genesis.json"

min-gas-price=0
sync-mode="FULL"
host-allowlist=["*"]

# identity
identity="qbft_node1"

#p2p-host="0.0.0.0"
p2p-port=30303

rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545

rpc-http-api=["ADMIN","NET","ETH","WEB3","QBFT","DEBUG","TRACE","TXPOOL"]
rpc-http-cors-origins=["*"]

rpc-http-authentication-enabled=false
rpc-http-authentication-jwt-public-key-file="./publicKey.pem"

rpc-ws-enabled=true
rpc-ws-port=8546

# https://besu.hyperledger.org/public-networks/how-to/connect/manage-peers
remote-connections-limit-enabled=false
random-peer-priority-enabled=true
revert-reason-enabled=true

# txpool (legacy)
#tx-pool-limit-by-account-percentage=0.4
#tx-pool-max-size=100
#tx-pool-price-bump=10
#tx-pool-retention-hours=1

#tx-pool-tx-inflow-control-enabled=true
#tx-pool-enterprise-pending-tx-sorter-enabled=true
